// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneDriveAccessGuard.Infrastructure.Data;

#nullable disable

namespace OneDriveAccessGuard.Infrastructure.Migrations
{
    [DbContext(typeof(AccessGuardDbContext))]
    partial class AccessGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OneDriveAccessGuard.Infrastructure.Data.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("OneDriveAccessGuard.Infrastructure.Data.ScanSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("HighRiskCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowRiskCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediumRiskCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalItemsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalUsersScanned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScanSessions", (string)null);
                });

            modelBuilder.Entity("OneDriveAccessGuard.Infrastructure.Data.SharedItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RiskLevel");

                    b.ToTable("SharedItems", (string)null);
                });

            modelBuilder.Entity("OneDriveAccessGuard.Infrastructure.Data.UserScanResultEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AllFiles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserScanResults", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
